# Generated by Django 2.2.15 on 2020-08-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': '1_Categories'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['create_date'], 'verbose_name_plural': '3_Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['create_date'], 'verbose_name': 'Quiz', 'verbose_name_plural': '2_Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quiztaker',
            options={'verbose_name_plural': '4_Quiz Takers'},
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='total_answers',
            field=models.IntegerField(default=0),
        ),
    ]
