# Generated by Django 2.2.15 on 2020-08-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0002_auto_20200814_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiztaker',
            old_name='total_answers',
            new_name='total_questions',
        ),
    ]
