# Generated by Django 2.2.15 on 2020-08-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0003_auto_20200815_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
