# Generated by Django 2.2.15 on 2020-08-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0004_auto_20200815_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztaker',
            name='start_date',
        ),
    ]
